package View;

import Controller.Controller;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

public class AnalisarFicheiro extends javax.swing.JPanel implements Runnable {

    Controller Controller;
    boolean NomeEstiloFirst = true, NomeFicheiroFirst = true;
    Thread T;
    JPanel CardPanel;

    public AnalisarFicheiro(Controller c) {
        Controller = c;
        Controller.setDnDFile(null);
        initComponents();
        LabelErroFicheiro.setVisible(false);
        jErroNomeEstilo1.setVisible(false);
        start();
    }

    public void setCardPanel(JPanel J) {
        CardPanel = J;
    }

    public void start() {
        if (T == null) {
            T = new Thread(this, "Thread1");
            T.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAnalisa = new javax.swing.JButton();
        TxtCaminho = new javax.swing.JTextField();
        BttnProcurar = new javax.swing.JButton();
        TxtNomeEstilo = new javax.swing.JTextField();
        CheckPermite = new javax.swing.JCheckBox();
        LabelErroFicheiro = new javax.swing.JLabel();
        jErroNomeEstilo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jAnalisa1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jAnalisa.setText("Analisar");
        jAnalisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAnalisaMouseClicked(evt);
            }
        });
        jAnalisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnalisaActionPerformed(evt);
            }
        });

        TxtCaminho.setForeground(new java.awt.Color(204, 204, 204));
        TxtCaminho.setText("C:\\Pasta1\\Pasta2\\exemplo.c");
        TxtCaminho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCaminhoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCaminhoFocusLost(evt);
            }
        });
        TxtCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCaminhoActionPerformed(evt);
            }
        });

        BttnProcurar.setText("Procurar");
        BttnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnProcurarActionPerformed(evt);
            }
        });

        TxtNomeEstilo.setForeground(new java.awt.Color(204, 204, 204));
        TxtNomeEstilo.setText("Nome Estilo Programação");
        TxtNomeEstilo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtNomeEstiloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtNomeEstiloFocusLost(evt);
            }
        });

        CheckPermite.setText("O meu estilo de programação pode ser utilizado por outros utilizadores");

        LabelErroFicheiro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelErroFicheiro.setForeground(new java.awt.Color(204, 0, 0));
        LabelErroFicheiro.setText("Introduza um ficheiro .c");

        jErroNomeEstilo1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jErroNomeEstilo1.setForeground(new java.awt.Color(204, 0, 0));
        jErroNomeEstilo1.setText("Nome de Estilo de Programação já Existente");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Analisar");

        jAnalisa1.setText("Converter");
        jAnalisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAnalisa1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jAnalisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jAnalisa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelErroFicheiro)
                                    .addComponent(jErroNomeEstilo1)
                                    .addComponent(TxtCaminho)
                                    .addComponent(TxtNomeEstilo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BttnProcurar))
                            .addComponent(CheckPermite))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BttnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelErroFicheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtNomeEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jErroNomeEstilo1)
                .addGap(18, 18, 18)
                .addComponent(CheckPermite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnalisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnalisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAnalisaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jAnalisaMouseClicked
    {//GEN-HEADEREND:event_jAnalisaMouseClicked
        if (Controller.isValidFile(TxtCaminho.getText()) && !Controller.ExisteNomeEstilo(TxtNomeEstilo.getText())) {
            Controller.Analisa(TxtCaminho.getText(), CheckPermite.isSelected(), TxtNomeEstilo.getText());
            jLabel2.setText("Ficheiro Analisado com sucesso!");
            jLabel2.setVisible(true);
        }
    }//GEN-LAST:event_jAnalisaMouseClicked

    private void TxtCaminhoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtCaminhoFocusGained
    {//GEN-HEADEREND:event_TxtCaminhoFocusGained
        if (NomeFicheiroFirst) {
            TxtCaminho.setText("");
        }
        TxtCaminho.setForeground(Color.BLACK);
        NomeFicheiroFirst = false;
    }//GEN-LAST:event_TxtCaminhoFocusGained

    private void TxtNomeEstiloFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtNomeEstiloFocusGained
    {//GEN-HEADEREND:event_TxtNomeEstiloFocusGained
        jLabel2.setVisible(false);
        if (NomeEstiloFirst) {
            TxtNomeEstilo.setText("");
        }
        TxtNomeEstilo.setForeground(Color.BLACK);
        NomeEstiloFirst = false;
    }//GEN-LAST:event_TxtNomeEstiloFocusGained

    private void TxtNomeEstiloFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtNomeEstiloFocusLost
    {//GEN-HEADEREND:event_TxtNomeEstiloFocusLost
        if (Controller.ExisteNomeEstilo(TxtNomeEstilo.getText())) {
            jErroNomeEstilo1.setVisible(true);
        }
    }//GEN-LAST:event_TxtNomeEstiloFocusLost

    private void TxtCaminhoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TxtCaminhoActionPerformed
    {//GEN-HEADEREND:event_TxtCaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCaminhoActionPerformed

    private void TxtCaminhoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtCaminhoFocusLost
    {//GEN-HEADEREND:event_TxtCaminhoFocusLost
        if (!Controller.isValidFile(TxtCaminho.getText())) {
            LabelErroFicheiro.setVisible(true);
        }
    }//GEN-LAST:event_TxtCaminhoFocusLost

    private void BttnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnProcurarActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Ficheiro .C", "c"));

        jLabel2.setVisible(false);
        
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                TxtCaminho.setText(fc.getSelectedFile().getCanonicalPath());
                TxtCaminho.setForeground(Color.black);
                NomeFicheiroFirst = false;
            } catch (IOException ex) {
            }
            LabelErroFicheiro.setVisible(false);
        }
    }//GEN-LAST:event_BttnProcurarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void jAnalisa1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jAnalisa1MouseClicked
    {//GEN-HEADEREND:event_jAnalisa1MouseClicked
        CardLayout cl = (CardLayout) CardPanel.getLayout();
        cl.next(CardPanel);
    }//GEN-LAST:event_jAnalisa1MouseClicked

    private void jAnalisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnalisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAnalisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnProcurar;
    private javax.swing.JCheckBox CheckPermite;
    private javax.swing.JLabel LabelErroFicheiro;
    private javax.swing.JTextField TxtCaminho;
    private javax.swing.JTextField TxtNomeEstilo;
    private javax.swing.JButton jAnalisa;
    private javax.swing.JButton jAnalisa1;
    private javax.swing.JLabel jErroNomeEstilo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

        File DnDFile = null;
        while (true) {
            try {
                File Aux = Controller.getDnDFile();

                if (DnDFile != Aux && Controller.isValidFile(Aux.getPath())) {
                    DnDFile = Controller.getDnDFile();
                } else {
                    continue;
                }

                if (DnDFile != null) {
                    if (NomeFicheiroFirst) {
                        TxtCaminho.setText("");
                    }
                    TxtCaminho.setForeground(Color.BLACK);
                    NomeFicheiroFirst = false;
                    TxtCaminho.setText(DnDFile.getCanonicalPath());
                }

            } catch (IOException ex) {
            }
        }

    }
}
