/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Tiago Coutinho
 */
public class AnalisarFicheiro extends javax.swing.JPanel
{
    Controller Controller;
    boolean NomeEstiloFirst=true, NomeFicheiroFirst=true;
    String Caminho;
    
    public AnalisarFicheiro(Controller c)
    {
        Controller=c;
        initComponents();
        LabelErroFicheiro.setVisible(false);
        jErroNomeEstilo1.setVisible(false);
        Caminho = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAnalisa = new javax.swing.JButton();
        TxtCaminho = new javax.swing.JTextField();
        BttnProcurar = new javax.swing.JButton();
        TxtNomeEstilo = new javax.swing.JTextField();
        CheckPermite = new javax.swing.JCheckBox();
        LabelErroFicheiro = new javax.swing.JLabel();
        jErroNomeEstilo1 = new javax.swing.JLabel();

        jAnalisa.setText("Analisar");
        jAnalisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAnalisaMouseClicked(evt);
            }
        });
        jAnalisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnalisaActionPerformed(evt);
            }
        });

        TxtCaminho.setForeground(new java.awt.Color(204, 204, 204));
        TxtCaminho.setText("C:\\Pasta1\\Pasta2\\exemplo.c");
        TxtCaminho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCaminhoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCaminhoFocusLost(evt);
            }
        });
        TxtCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCaminhoActionPerformed(evt);
            }
        });

        BttnProcurar.setText("Procurar");
        BttnProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnProcurarMouseClicked(evt);
            }
        });
        BttnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnProcurarActionPerformed(evt);
            }
        });

        TxtNomeEstilo.setForeground(new java.awt.Color(204, 204, 204));
        TxtNomeEstilo.setText("Nome Estilo Programação");
        TxtNomeEstilo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtNomeEstiloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtNomeEstiloFocusLost(evt);
            }
        });

        CheckPermite.setText("O meu estilo de programação pode ser utilizado por outros utilizadores");

        LabelErroFicheiro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelErroFicheiro.setForeground(new java.awt.Color(204, 0, 0));
        LabelErroFicheiro.setText("Introduza um ficheiro .c");

        jErroNomeEstilo1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jErroNomeEstilo1.setForeground(new java.awt.Color(204, 0, 0));
        jErroNomeEstilo1.setText("Nome de Estilo de Programação já Existente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNomeEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelErroFicheiro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BttnProcurar))
                    .addComponent(jErroNomeEstilo1))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CheckPermite))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jAnalisa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BttnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelErroFicheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtNomeEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jErroNomeEstilo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckPermite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAnalisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAnalisaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jAnalisaMouseClicked
    {//GEN-HEADEREND:event_jAnalisaMouseClicked
            if(Controller.isValidFile(TxtCaminho.getText()) && !Controller.ExisteNomeEstilo(TxtNomeEstilo.getText()))
        Controller.Analisa(TxtCaminho.getText(), CheckPermite.isSelected(), TxtNomeEstilo.getText());
    }//GEN-LAST:event_jAnalisaMouseClicked

    private void TxtCaminhoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtCaminhoFocusGained
    {//GEN-HEADEREND:event_TxtCaminhoFocusGained
        if(NomeFicheiroFirst)
            TxtCaminho.setText("");
        TxtCaminho.setForeground(Color.BLACK);
        NomeFicheiroFirst=false;
    }//GEN-LAST:event_TxtCaminhoFocusGained

    private void TxtNomeEstiloFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtNomeEstiloFocusGained
    {//GEN-HEADEREND:event_TxtNomeEstiloFocusGained
        if(NomeEstiloFirst)
            TxtNomeEstilo.setText("");
        TxtNomeEstilo.setForeground(Color.BLACK);
        NomeEstiloFirst=false;
    }//GEN-LAST:event_TxtNomeEstiloFocusGained

    private void TxtNomeEstiloFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtNomeEstiloFocusLost
    {//GEN-HEADEREND:event_TxtNomeEstiloFocusLost
        if(!Controller.ExisteNomeEstilo(TxtNomeEstilo.getText()))
            jErroNomeEstilo1.setVisible(true);
    }//GEN-LAST:event_TxtNomeEstiloFocusLost

    private void TxtCaminhoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TxtCaminhoActionPerformed
    {//GEN-HEADEREND:event_TxtCaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCaminhoActionPerformed

    private void TxtCaminhoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_TxtCaminhoFocusLost
    {//GEN-HEADEREND:event_TxtCaminhoFocusLost
        if(!Controller.isValidFile(TxtCaminho.getText()))
            LabelErroFicheiro.setVisible(true);
    }//GEN-LAST:event_TxtCaminhoFocusLost

    private void BttnProcurarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BttnProcurarMouseClicked
    {//GEN-HEADEREND:event_BttnProcurarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BttnProcurarMouseClicked

    private void jAnalisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnalisaActionPerformed
        Controller.Analisa(Caminho, CheckPermite.isEnabled(), TxtNomeEstilo.getText());
    }//GEN-LAST:event_jAnalisaActionPerformed

    private void BttnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnProcurarActionPerformed
        JFileChooser fc = new JFileChooser();
        
        int ReturnValue = fc.showOpenDialog(this);
        
        if (ReturnValue == JFileChooser.APPROVE_OPTION){
            try {
                TxtCaminho.setText(fc.getSelectedFile().getCanonicalPath());
            } catch (IOException ex) {            }
            Caminho = TxtCaminho.getText();
            LabelErroFicheiro.setVisible(false);
        }
        else{
            LabelErroFicheiro.setVisible(true);
        }
    }//GEN-LAST:event_BttnProcurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnProcurar;
    private javax.swing.JCheckBox CheckPermite;
    private javax.swing.JLabel LabelErroFicheiro;
    private javax.swing.JTextField TxtCaminho;
    private javax.swing.JTextField TxtNomeEstilo;
    private javax.swing.JButton jAnalisa;
    private javax.swing.JLabel jErroNomeEstilo1;
    // End of variables declaration//GEN-END:variables
}
