package View;

import Controller.Controller;
import Model.EstiloProgramacao.EstiloProgramacao;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class ConverterDiretoria extends javax.swing.JPanel implements Runnable {

    Controller Controller;
    Thread T;

    public ConverterDiretoria(Controller Controller) {
        this.Controller = Controller;
        initComponents();

        if (Controller.getEstilosUtilizador() != null) {
            for (EstiloProgramacao EP : Controller.getEstilosUtilizador()) {
                jListaEstilos.add(EP.getNome());
            }
        }

        start();
    }

    public void start() {
        if (T == null) {
            T = new Thread(this, "Thread2");
            T.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jConverter = new javax.swing.JButton();
        jDiretoria = new javax.swing.JTextField();
        jProcurar = new javax.swing.JButton();
        jListaEstilos = new java.awt.Choice();
        jEscolherOutro = new javax.swing.JButton();

        jConverter.setText("Converter");
        jConverter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jConverterMouseClicked(evt);
            }
        });

        jDiretoria.setForeground(new java.awt.Color(204, 204, 204));
        jDiretoria.setText("C:\\Pasta1\\Pasta2");

        jProcurar.setText("Procurar");
        jProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProcurarActionPerformed(evt);
            }
        });

        jEscolherOutro.setText("Escolher Outro");
        jEscolherOutro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEscolherOutroMouseClicked(evt);
            }
        });
        jEscolherOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolherOutroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jListaEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEscolherOutro))
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jDiretoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProcurar)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiretoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jListaEstilos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEscolherOutro, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jEscolherOutroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jEscolherOutroActionPerformed
    {//GEN-HEADEREND:event_jEscolherOutroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEscolherOutroActionPerformed

    private void jEscolherOutroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jEscolherOutroMouseClicked
    {//GEN-HEADEREND:event_jEscolherOutroMouseClicked
    }//GEN-LAST:event_jEscolherOutroMouseClicked

    private void jConverterMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jConverterMouseClicked
    {//GEN-HEADEREND:event_jConverterMouseClicked
        if (Controller.ExisteNomeEstilo(jListaEstilos.getSelectedItem())) {
            Controller.Converte(jDiretoria.getText(), jListaEstilos.getSelectedItem(), Controller.getUtilizadorAtualNome());
        }
    }//GEN-LAST:event_jConverterMouseClicked
  
    private void jProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcurarActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                jDiretoria.setText(fc.getSelectedFile().getCanonicalPath());
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_jProcurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jConverter;
    private javax.swing.JTextField jDiretoria;
    private javax.swing.JButton jEscolherOutro;
    private java.awt.Choice jListaEstilos;
    private javax.swing.JButton jProcurar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        File DnDFile = null;
        while (true) {
            try {
                File Aux = Controller.getDnDFile();
                if (DnDFile != Aux && Controller.IsDiretorio(Aux)) {
                    DnDFile = Controller.getDnDFile();
                } else {
                    continue;
                }

                if (DnDFile != null) {
                    jDiretoria.setText(DnDFile.getCanonicalPath());
                }
            } catch (IOException ex) {
            }
        }

    }
}
